### ISSUE TITLE
Storage aircraft_db.csv in MongoDB database

### ISSUE THREAD

**Issue by CHMBroeders** [junzis/aircraft-id-finder#4]
is it possible to insert the content of the file "aircraft_db.csv" in a "MongoDB" database?
Best greetings,
C. BroedersStorage

**Comment by CHMBroeders** [comment]
Objective is to extent the available huge file with own automatic downloads.
C. Broeders

**Comment by junzis** [comment]
yes, you can user `mongoimport --type csv`

**Comment by CHMBroeders** [comment]
Would it be possible to give a short example how to install a usuable mongodb environment  starting from your large aircraft_db.csv file to extent it with your cron*.py procedures?

**Comment by junzis** [comment]
@CHMBroeders, I think this is out of the scope of the tool. What's more is that there are some fields pointing to fr24 in my Mongodb that are not exported. This is due to the concern of licensing of fr24 data. However, the base of this tool is open source, that everyone can customize it as they wanted. 

Also be very aware of the licensing agreement of fr24 (https://www.flightradar24.com/terms-and-conditions). Data provide from my website is free of license because we are a contributor. But you need to check if yourself have the right to use/distribute those data if they are obtained from your setup.

**Comment by CHMBroeders** [comment]
Thank you very much for this info. I had a small hope that it would be possible to extent your huge file automatically with running aircraft_db.git application on my server. 
In the meantime I have valid fr24 license. 
After about 2 weeks, my local aircraft_db.csv file is about one third of the huge file.
Thank you for this interesting application for collecting plane infos.

**Comment by junzis** [comment]
@CHMBroeders, You are welcome. I am glad the tool is useful. Simply leave the tool running for a month or two, then you should have captured most of the airplanes.

**Comment by CHMBroeders** [comment]
Thanks, I will observe carefully and report significant results
